[package]
name = "quinn-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
quinn = "0.11.9"
rustls = { version = "0.23.35", features = ["aws-lc-rs"] }
tokio = { version = "1.48.0", features = ["full"] }
